
public enum UnitSystem
{
    NONE,
    METRIC = 0,
    IMPERIAL = 1
}

public enum DisplayUnit
{
    INVALID,
    UNITLESS,
    MILLIMETER,
    CENTIMETER,
    METER,
    KILOMETER,
    INCH,
    FOOT,
    PASCAL,
    KILOPASCAL,
    MEGAPASCAL,
    GIGAPASCAL,
    POUND_PER_SQUARE_INCH,
    KIP_PER_SQUARE_INCH,
    POUND_PER_SQUARE_FOOT,
    KIP_PER_SQUARE_FOOT,
    NEWTON,
    KILONEWTON,
    MEGANEWTON,
    POUND,
    KIP,
    SQUARE_MILLIMETER,
    SQUARE_CENTIMETER,
    SQUARE_METER,
    SQUARE_KILOMETER,
    SQUARE_INCH,
    SQUARE_FOOT,
    CUBIC_MILLIMETER,
    CUBIC_METER,
    CUBIC_KILOMETER,
    CUBIC_INCH,
    CUBIC_FOOT,
    NEWTON_PER_MILLIMETER,
    KILONEWTON_PER_MILLIMETER,
    MEGANEWTON_PER_MILLIMETER,
    GIGANEWTON_PER_MILLIMETER

}

public enum UnitType
{
    NONE,
    LENGTH = 0,
    STRESS = 1,
    FORCE = 2,
    FORCE_PER_UNIT_LENGTH = 3,
    MOMENT = 4,
    AREA,
    VOLUME
}
